// entel_frontend/resources/js/Components/Forms/SelectInput.vue
<script setup>
import { computed } from 'vue';

const props = defineProps({
    modelValue: [String, Number],
    label: String,
    options: {
        type: Array,
        default: () => [],
        // [{ value: 1, label: 'Option 1' }]
    },
    placeholder: String,
    error: String,
    required: Boolean,
    disabled: Boolean,
});

const emit = defineEmits(['update:modelValue']);

const value = computed({
    get: () => props.modelValue,
    set: (val) => emit('update:modelValue', val),
});
</script>

<template>
    <div class="space-y-2">
        <label v-if="label" class="block text-sm font-outfit font-medium text-white/80">
            {{ label }}
            <span v-if="required" class="text-entel-orange">*</span>
        </label>
        <select
            v-model="value"
            :disabled="disabled"
            :class="[
                'w-full px-4 py-3 bg-white/5 border rounded-xl text-white font-outfit text-sm transition-all duration-200 appearance-none',
                'focus:outline-none focus:ring-2',
                error
                    ? 'border-red-500/50 focus:border-red-500 focus:ring-red-500/20'
                    : 'border-white/10 focus:border-entel-orange/50 focus:ring-entel-orange/20',
                disabled ? 'opacity-50 cursor-not-allowed' : '',
            ]"
            style="background-image: url('data:image/svg+xml;charset=UTF-8,%3csvg xmlns=%27http://www.w3.org/2000/svg%27 viewBox=%270 0 24 24%27 fill=%27none%27 stroke=%27rgba(255,255,255,0.5)%27 stroke-width=%272%27 stroke-linecap=%27round%27 stroke-linejoin=%27round%27%3e%3cpolyline points=%276 9 12 15 18 9%27%3e%3c/polyline%3e%3c/svg%3e'); background-repeat: no-repeat; background-position: right 1rem center; background-size: 1em;"
        >
            <option v-if="placeholder" value="" disabled class="bg-gray-900">{{ placeholder }}</option>
            <option
                v-for="opt in options"
                :key="opt.value"
                :value="opt.value"
                class="bg-gray-900"
            >
                {{ opt.label }}
            </option>
        </select>
        <p v-if="error" class="text-sm text-red-400 font-outfit">{{ error }}</p>
    </div>
</template>

// frontend/src/components/forms/SelectInput.tsx
interface SelectOption {
  value: string | number
  label: string
}

interface SelectInputProps {
  label?: string
  name: string
  value: string | number
  onChange: (value: string) => void
  options: SelectOption[]
  placeholder?: string
  error?: string
  required?: boolean
  disabled?: boolean
}

export default function SelectInput({
  label,
  name,
  value,
  onChange,
  options,
  placeholder,
  error,
  required = false,
  disabled = false,
}: SelectInputProps) {
  return (
    <div className="space-y-1.5">
      {label && (
        <label htmlFor={name} className="block text-sm font-sans font-medium text-white/70">
          {label}
          {required && <span className="text-red-400 ml-1">*</span>}
        </label>
      )}
      <select
        id={name}
        name={name}
        value={value}
        onChange={(e) => onChange(e.target.value)}
        disabled={disabled}
        required={required}
        className={`
          w-full bg-white/5 border rounded-xl px-4 py-2.5
          text-white font-sans appearance-none
          focus:outline-none focus:ring-2 transition-all duration-200
          ${disabled ? 'opacity-50 cursor-not-allowed' : ''}
          ${
            error
              ? 'border-red-500/50 focus:ring-red-500/30 focus:border-red-500/50'
              : 'border-white/10 focus:ring-entel-orange/50 focus:border-entel-orange/50'
          }
        `}
        style={{
          backgroundImage: `url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='12' viewBox='0 0 24 24' fill='none' stroke='rgba(255,255,255,0.4)' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpolyline points='6 9 12 15 18 9'%3E%3C/polyline%3E%3C/svg%3E")`,
          backgroundRepeat: 'no-repeat',
          backgroundPosition: 'right 12px center',
          paddingRight: '2.5rem',
        }}
      >
        {placeholder && (
          <option value="" className="bg-[#1a1a24] text-white/50">
            {placeholder}
          </option>
        )}
        {options.map((opt) => (
          <option key={opt.value} value={opt.value} className="bg-[#1a1a24] text-white">
            {opt.label}
          </option>
        ))}
      </select>
      {error && (
        <p className="text-xs text-red-400 font-sans mt-1">{error}</p>
      )}
    </div>
  )
}
