// entel_frontend/resources/js/Pages/ConfigAvanzada/Operadores.vue
<script setup>
import { ref, computed, watch } from 'vue';
import { Head, router, usePage } from '@inertiajs/vue3';
import AppLayout from '@/Components/Layout/AppLayout.vue';
import DataTable from '@/Components/UI/DataTable.vue';
import Modal from '@/Components/UI/Modal.vue';
import Button from '@/Components/UI/Button.vue';
import Card from '@/Components/UI/Card.vue';
import TextInput from '@/Components/Forms/TextInput.vue';
import Toast from '@/Components/UI/Toast.vue';

const props = defineProps({ operadores: Array });
const page = usePage();
const loading = ref(false);
const showModal = ref(false);
const editing = ref(null);
const form = ref({ nombre: '', codigo: '' });
const errors = ref({});

// Toast state
const toast = ref({
    show: false,
    type: 'error',
    message: ''
});

// Obtener errores del servidor y mostrar toast
const pageErrors = computed(() => page.props.errors || {});

watch(pageErrors, (newErrors) => {
    if (newErrors.message) {
        showToast('error', newErrors.message);
    }
}, { immediate: true });

const showToast = (type, message) => {
    toast.value = { show: true, type, message };
};

const hideToast = () => {
    toast.value.show = false;
};

const columns = [
    { key: 'id_operador_telefonico', label: 'ID', sortable: true },
    { key: 'nombre', label: 'Nombre', sortable: true },
    { key: 'codigo', label: 'Código', sortable: true },
];

const openCreate = () => { editing.value = null; form.value = { nombre: '', codigo: '' }; errors.value = {}; showModal.value = true; };
const openEdit = (item) => { editing.value = item; form.value = { nombre: item.nombre, codigo: item.codigo }; errors.value = {}; showModal.value = true; };
const closeModal = () => { showModal.value = false; editing.value = null; errors.value = {}; };

const save = () => {
    if (!form.value.nombre.trim()) {
        errors.value = { nombre: 'El nombre es requerido' };
        return;
    }
    loading.value = true;
    const url = editing.value ? `/configuracion-avanzada/operadores-telefonicos/${editing.value.id_operador_telefonico}` : '/configuracion-avanzada/operadores-telefonicos';
    router[editing.value ? 'put' : 'post'](url, form.value, {
        preserveScroll: true,
        onSuccess: () => {
            closeModal();
            loading.value = false;
            showToast('success', editing.value ? 'Operador actualizado correctamente' : 'Operador creado correctamente');
        },
        onError: (err) => {
            errors.value = err;
            loading.value = false;
        },
    });
};

const remove = (item) => {
    if (confirm(`¿Estás seguro de eliminar "${item.nombre}"?\n\nEsta acción no se puede deshacer.`)) {
        loading.value = true;
        router.delete(`/configuracion-avanzada/operadores-telefonicos/${item.id_operador_telefonico}`, {
            preserveScroll: true,
            onSuccess: () => {
                loading.value = false;
                showToast('success', 'Operador eliminado correctamente');
            },
            onError: (err) => {
                loading.value = false;
            },
        });
    }
};
</script>

<template>
    <Head title="Operadores Telefónicos" />
    <AppLayout title="Operadores Telefónicos">
        <!-- Toast Notification -->
        <Toast
            :show="toast.show"
            :type="toast.type"
            :message="toast.message"
            @close="hideToast"
        />

        <Card>
            <template #header>
                <div class="flex items-center justify-between">
                    <div>
                        <h3 class="text-lg font-outfit font-semibold text-white">Operadores</h3>
                        <p class="text-sm text-white/50">Administra los operadores telefónicos</p>
                    </div>
                    <Button @click="openCreate" variant="primary">+ Nuevo Operador</Button>
                </div>
            </template>
            <DataTable :columns="columns" :data="operadores || []" :loading="loading">
                <template #actions="{ row }">
                    <div class="flex gap-1 justify-end">
                        <button @click.stop="openEdit(row)" class="p-2 rounded-lg text-white/50 hover:text-orange-400 hover:bg-orange-400/10 transition-all" title="Editar">
                            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"/>
                            </svg>
                        </button>
                        <button @click.stop="remove(row)" class="p-2 rounded-lg text-white/50 hover:text-red-400 hover:bg-red-400/10 transition-all" title="Eliminar">
                            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"/>
                            </svg>
                        </button>
                    </div>
                </template>
            </DataTable>
        </Card>
        <Modal :show="showModal" :title="editing ? 'Editar Operador' : 'Nuevo Operador'" @close="closeModal">
            <form @submit.prevent="save" class="space-y-4">
                <TextInput v-model="form.nombre" label="Nombre" :error="errors.nombre" placeholder="Ej: Entel, Claro, Movistar" required />
                <TextInput v-model="form.codigo" label="Código" :error="errors.codigo" placeholder="Ej: ENT, CLA, MOV" />
            </form>
            <template #footer>
                <Button @click="closeModal" variant="ghost">Cancelar</Button>
                <Button @click="save" variant="primary" :loading="loading">{{ editing ? 'Actualizar' : 'Crear' }}</Button>
            </template>
        </Modal>
    </AppLayout>
</template>

// frontend/src/pages/avanzada/Operadores.tsx
import { useState, useCallback, useEffect } from 'react'
import { useCrud } from '../../hooks/useCrud'
import { useToast } from '../../components/ui/Toast'
import DataTable, { type Column } from '../../components/ui/DataTable'
import Modal from '../../components/ui/Modal'
import Button from '../../components/ui/Button'
import TextInput from '../../components/forms/TextInput'
import {
  getOperadores,
  createOperador,
  updateOperador,
  deleteOperador,
  getTecnologias,
  type Operador,
  type Tecnologia,
} from '../../api/config-avanzada'

interface FormData {
  nombre: string
  codigo: string
  tecnologias: number[]
}

const emptyForm: FormData = {
  nombre: '',
  codigo: '',
  tecnologias: [],
}

export default function Operadores() {
  const { addToast } = useToast()

  const fetchOperadores = useCallback(() => getOperadores(), [])
  const { data: operadores, loading, refetch } = useCrud<Operador[]>(fetchOperadores, { refreshInterval: 24000 })

  const fetchTecnologias = useCallback(() => getTecnologias(), [])
  const { data: tecnologias } = useCrud<Tecnologia[]>(fetchTecnologias)

  const [modalOpen, setModalOpen] = useState(false)
  const [deleteModalOpen, setDeleteModalOpen] = useState(false)
  const [editingId, setEditingId] = useState<number | null>(null)
  const [deleteId, setDeleteId] = useState<number | null>(null)
  const [form, setForm] = useState<FormData>(emptyForm)
  const [saving, setSaving] = useState(false)
  const [deleting, setDeleting] = useState(false)

  useEffect(() => {
    if (!modalOpen) {
      setForm(emptyForm)
      setEditingId(null)
    }
  }, [modalOpen])

  const handleCreate = () => {
    setEditingId(null)
    setForm(emptyForm)
    setModalOpen(true)
  }

  const handleEdit = (op: Operador) => {
    setEditingId(op.id_operador_telefonico)
    setForm({
      nombre: op.nombre,
      codigo: op.codigo || '',
      tecnologias: op.tecnologias?.map((t) => t.id_tecnologia) || [],
    })
    setModalOpen(true)
  }

  const handleDeleteClick = (id: number) => {
    setDeleteId(id)
    setDeleteModalOpen(true)
  }

  const toggleTecnologia = (tecId: number) => {
    setForm((f) => ({
      ...f,
      tecnologias: f.tecnologias.includes(tecId)
        ? f.tecnologias.filter((id) => id !== tecId)
        : [...f.tecnologias, tecId],
    }))
  }

  const handleSave = async () => {
    if (!form.nombre.trim()) {
      addToast('warning', 'El nombre del operador es obligatorio')
      return
    }

    setSaving(true)
    try {
      if (editingId) {
        const res = await updateOperador(editingId, {
          nombre: form.nombre,
          codigo: form.codigo,
          tecnologias: form.tecnologias,
        })
        if (res.estado) {
          addToast('success', 'Operador actualizado correctamente')
          setModalOpen(false)
          refetch()
        } else {
          addToast('error', res.error || 'Error al actualizar operador')
        }
      } else {
        const res = await createOperador({
          nombre: form.nombre,
          codigo: form.codigo,
          tecnologias: form.tecnologias,
        })
        if (res.estado) {
          addToast('success', 'Operador creado correctamente')
          setModalOpen(false)
          refetch()
        } else {
          addToast('error', res.error || 'Error al crear operador')
        }
      }
    } catch (err) {
      addToast('error', err instanceof Error ? err.message : 'Error inesperado')
    } finally {
      setSaving(false)
    }
  }

  const handleDelete = async () => {
    if (!deleteId) return
    setDeleting(true)
    try {
      const res = await deleteOperador(deleteId)
      if (res.estado) {
        addToast('success', 'Operador eliminado correctamente')
        setDeleteModalOpen(false)
        setDeleteId(null)
        refetch()
      } else {
        addToast('error', res.error || 'Error al eliminar operador')
      }
    } catch (err) {
      addToast('error', err instanceof Error ? err.message : 'Error inesperado')
    } finally {
      setDeleting(false)
    }
  }

  const columns: Column<Operador>[] = [
    { key: 'id_operador_telefonico', label: 'ID', sortable: true },
    { key: 'nombre', label: 'Nombre', sortable: true },
    {
      key: 'codigo',
      label: 'Codigo',
      sortable: true,
      render: (row) => (
        <span className="font-mono text-white/60">{row.codigo || '-'}</span>
      ),
    },
    {
      key: '_tecnologias',
      label: 'Tecnologias',
      sortable: false,
      render: (row) => (
        <div className="flex flex-wrap gap-1.5">
          {row.tecnologias && row.tecnologias.length > 0 ? (
            row.tecnologias.map((tec) => (
              <span
                key={tec.id_tecnologia}
                className="px-2 py-0.5 rounded-md bg-purple-500/10 border border-purple-500/20 text-purple-400 text-xs font-sans"
              >
                {tec.nombre}
              </span>
            ))
          ) : (
            <span className="text-white/30 text-xs">Sin tecnologias</span>
          )}
        </div>
      ),
    },
    {
      key: '_actions',
      label: 'Acciones',
      sortable: false,
      render: (row) => (
        <div className="flex items-center gap-2">
          <button
            onClick={(e) => {
              e.stopPropagation()
              handleEdit(row)
            }}
            className="p-1.5 rounded-lg text-white/40 hover:text-entel-orange hover:bg-entel-orange/10 transition-all"
            title="Editar"
          >
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"
              />
            </svg>
          </button>
          <button
            onClick={(e) => {
              e.stopPropagation()
              handleDeleteClick(row.id_operador_telefonico)
            }}
            className="p-1.5 rounded-lg text-white/40 hover:text-red-400 hover:bg-red-500/10 transition-all"
            title="Eliminar"
          >
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"
              />
            </svg>
          </button>
        </div>
      ),
    },
  ]

  return (
    <div className="space-y-6">
      {/* Page header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-sans font-bold text-white">Operadores</h1>
          <p className="text-white/50 text-sm font-sans mt-1">
            Administracion de operadores telefonicos
          </p>
        </div>
        <Button onClick={handleCreate}>
          <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
          </svg>
          Nuevo Operador
        </Button>
      </div>

      {/* Data table */}
      <DataTable
        columns={columns}
        data={operadores || []}
        loading={loading}
      />

      {/* Create/Edit modal */}
      <Modal
        isOpen={modalOpen}
        onClose={() => setModalOpen(false)}
        title={editingId ? 'Editar Operador' : 'Nuevo Operador'}
        size="md"
        footer={
          <>
            <Button variant="secondary" onClick={() => setModalOpen(false)}>
              Cancelar
            </Button>
            <Button onClick={handleSave} loading={saving}>
              {editingId ? 'Actualizar' : 'Crear'}
            </Button>
          </>
        }
      >
        <div className="space-y-4">
          <TextInput
            label="Nombre"
            name="nombre"
            value={form.nombre}
            onChange={(val) => setForm((f) => ({ ...f, nombre: val }))}
            placeholder="Ej: Claro, Movistar, Entel"
            required
          />
          <TextInput
            label="Codigo"
            name="codigo"
            value={form.codigo}
            onChange={(val) => setForm((f) => ({ ...f, codigo: val }))}
            placeholder="Codigo del operador (ej: ENT, CLA, MOV)"
          />

          {/* Tecnologias checkbox list */}
          <div className="space-y-1.5">
            <label className="block text-sm font-sans font-medium text-white/70">
              Tecnologias asociadas
            </label>
            <div className="space-y-2 max-h-[200px] overflow-y-auto rounded-xl border border-white/10 p-4 bg-white/[0.02]">
              {(tecnologias || []).length === 0 ? (
                <p className="text-white/40 text-sm font-sans">Cargando tecnologias...</p>
              ) : (
                (tecnologias || []).map((tec) => (
                  <label key={tec.id_tecnologia} className="flex items-center gap-3 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={form.tecnologias.includes(tec.id_tecnologia)}
                      onChange={() => toggleTecnologia(tec.id_tecnologia)}
                      className="w-4 h-4 rounded border-white/20 bg-white/5 text-entel-orange focus:ring-entel-orange/50 focus:ring-2"
                    />
                    <span className="text-sm font-sans text-white/70">{tec.nombre}</span>
                  </label>
                ))
              )}
            </div>
          </div>
        </div>
      </Modal>

      {/* Delete confirmation modal */}
      <Modal
        isOpen={deleteModalOpen}
        onClose={() => setDeleteModalOpen(false)}
        title="Confirmar Eliminacion"
        size="sm"
        footer={
          <>
            <Button variant="secondary" onClick={() => setDeleteModalOpen(false)}>
              Cancelar
            </Button>
            <Button variant="danger" onClick={handleDelete} loading={deleting}>
              Eliminar
            </Button>
          </>
        }
      >
        <p className="text-white/70 font-sans text-sm">
          Esta seguro de que desea eliminar este operador? Esta accion no se puede deshacer.
        </p>
      </Modal>
    </div>
  )
}
